    # def test_history_1_entry(self):
    #     self.terminal.history_length = 1
    #     self.assertEqual(self.command.mode, Mode.NORMAL)

    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)
    #     self.terminal.history.assert_called_once_with(0)
    #     self.terminal.history_start.assert_called_once_with()

    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)
    #     self.terminal.history.assert_called_once_with(0)
    #     self.terminal.history_start.assert_called_once_with()

    #     self.command(curses.KEY_DOWN)
    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.assertEqual(self.command.mode, Mode.NORMAL)
    #     self.terminal.history.assert_called_once_with(0)
    #     self.terminal.history_stop.assert_called_once_with()

    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.assertEqual(self.command.mode, Mode.NORMAL)
    #     self.terminal.history.assert_called_once_with(0)
    #     self.terminal.history_stop.assert_called()

    # def test_history_several_entry(self):
    #     self.terminal.history_length = 5
    #     self.assertEqual(self.command.mode, Mode.NORMAL)

    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 4)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)
    #     self.terminal.history.assert_called_once_with(4)

    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 3)
    #     self.terminal.history.assert_called_with(3)
    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 2)
    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 1)
    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.terminal.history.assert_called_with(0)
    #     self.command(curses.KEY_UP)
    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.terminal.history.assert_called_with(0)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)

    #     self.command(curses.KEY_DOWN)
    #     self.assertEqual(self.command.mode_idx, 1)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)
    #     self.command(curses.KEY_DOWN)
    #     self.assertEqual(self.command.mode_idx, 2)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)
    #     self.command(curses.KEY_DOWN)
    #     self.assertEqual(self.command.mode_idx, 3)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)
    #     self.command(curses.KEY_DOWN)
    #     self.assertEqual(self.command.mode_idx, 4)
    #     self.assertEqual(self.command.mode, Mode.HISTORY)
    #     self.command(curses.KEY_DOWN)
    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.assertEqual(self.command.mode, Mode.NORMAL)
    #     self.command(curses.KEY_DOWN)
    #     self.assertEqual(self.command.mode_idx, 0)
    #     self.assertEqual(self.command.mode, Mode.NORMAL)
